
help:  ## Show help
	@grep -E '^[.a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

train: ## Train the model
	python src/train.py

evaluate: ## evaluate global similarity vectors
	python src/evaluate.py

evaluate16: ## evaluate final cache for snippet size 16 x 16
	python src/evaluate.py experiment=16_patch

evaluate32: ## evaluate final cache for snippet size 32 x 32
	python src/evaluate.py experiment=32_patch

evaluate64: ## evaluate final cache for snippet size 64 x 64
	python src/evaluate.py experiment=64_patch

clip_cache: ## create clip cache for global similarity vectors
	python src/clip_cache.py

voc2012: ## download the pascal voc 2012 dataset
	python src/data/voc.py

clip_cache16: ## create clip cache for snippet size = 16 x 16
	python src/clip_cache.py experiment=16_patch

clip_cache32: ## create clip cache for snippet size = 32 x 32
	python src/clip_cache.py experiment=32_patch

clip_cache64: ## create clip cache for snippet size = 64 x 64
	python src/clip_cache.py experiment=64_patch