# @package _global_

# specify default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  # - logger: wandb
  - paths: voc2012
  - data: voc2012
  - hydra: default
  - model: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  # - hparams_search: null

# task name, determines output directory path (for logs)
task_name: "clip_cache"

# config for creating CLIP cache vectors
clip_cache:
  batch_size: 8
  thresh: 0.5
  snippet_size: 3
  global_cache_dir: ${paths.cache_save_root}/clip_cache/model_${model.clip.name}/global
  aggregate_cache_dir: ${clip_cache.global_cache_dir}/thresh_${clip_cache.thresh}/snippet_size_${clip_cache.snippet_size}/aggregate

evaluate: 
  mode: "global" # mode of CLIP cache to evaluate
  batch_size: 8
  num_workers: 4